global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
          - cadvisor:8080

  # Monitoreando servicios de microservicios
  - job_name: microservices
    scrape_interval: 15s
    static_configs:
      - targets:
          - auth-api:8000
          - users-api:8080
          - todos-api:8082
          - frontend:8080